#!/bin/bash

IFS=';;;;'
envs=(`cat /proc/1/environ | xargs -0 -n 1 echo ';;;;'`)
unset IFS

for _curVar in "${envs[@]}"
do
    value=`echo "$_curVar" | awk -F = '{print $2}'`
    name=`echo "$_curVar" | awk -F = '{print $1}' | xargs`
    if [ "$name" == "" ]
    then
      continue
    fi

  if [ "$name" == "GITHOST" ]
  then
    GITHOST="$value"
  fi
  if [ "$name" == "DEVUSER" ]
  then
    DEVUSER="$value"
  fi
  if [ "$name" == "DEVPASS" ]
  then
    DEVPASS="$value"
  fi
done

useradd -d /var/www/html -G www-data -s /bin/bash $DEVUSER
echo "$DEVUSER:$DEVPASS" | chpasswd
echo "$DEVUSER ALL=(ALL) NOPASSWD: /usr/bin/setfacl" > /etc/sudoers.d/ssh_user

GITH="`echo $GITHOST | awk -F: '{ print $1 }'`"
GITP="`echo $GITHOST | awk -F: '{ print $2 }'`"
if [ "$GITP" == "" ]
then
  GITP=22
fi

mkdir /var/www/html/.ssh
cp /key /var/www/html/.ssh/deploykey 
chmod 600 /var/www/html/.ssh/deploykey 
touch /var/www/html/.ssh/config 
chmod 600 /var/www/html/.ssh/config 
echo "Host $GITH" >>/var/www/html/.ssh/config
echo "  IdentityFile /var/www/html/.ssh/deploykey" >>/var/www/html/.ssh/config
echo "  Port $GITP" >>/var/www/html/.ssh/config
ssh-keyscan -p $GITP -v $GITH >> /var/www/html/.ssh/known_hosts
chown dev -R /var/www/html/.ssh
